# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=30)),
                ('store_manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ims.Manager')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ims.Item')),
                ('_quantity', models.IntegerField()),
                ('inv_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_item_rel', to='ims.Item')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_id_rel', to='ims.Store')),
            ],
            bases=('ims.item',),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=set([('inv_item', 'store_id')]),
        ),
    ]
