# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='lname',
        ),
    ]
