# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_qty', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.Item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ims.Store')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='inv_item',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='item_ptr',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='store_id',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.AddField(
            model_name='store',
            name='items',
            field=models.ManyToManyField(through='ims.StoreItem', to='ims.Item'),
        ),
    ]
