# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_auto_20170305_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='_qty',
            new_name='qty',
        ),
    ]
