# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 23:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims', '0002_auto_20170423_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, default='DEFAULT DESCRIPTION', max_length=30),
        ),
        migrations.AddField(
            model_name='manager',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 23, 16, 2, 39, 923226)),
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, default='Dream St', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, default='555-555-5555', max_length=20),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
